# aws-lb-serviceaccount.yaml
apiVersion: v1
kind: ServiceAccount
metadata:
  name: aws-load-balancer-controller
  namespace: kube-system
  annotations:
    eks.amazonaws.com/role-arn: arn:aws:iam::688567307365:role/eksctl-stage-eks-cluster-addon-aws-load-balancer-controller-Role1-XXXXXX