# Default values for hello-k8s production deployment.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.

# Namespace for the staging deployment
namespace: app-staging-alb

# Replica count for the staging deployment
replicaCount: 2

# Staging image configuration
image:
  repository: tiagovedana/hello-k8s                                                                         # Docker repository for the staging image    
  tag: staging                                                                                              # Staging image tag
  pullPolicy: IfNotPresent                                                                                  # Image pull policy for staging

# Staging application configuration
app:
  name: hello-world-staging-alb                                                                             # Application name for staging
  port: 5000                                                                                                # Port on which the application listens in staging
  env: staging                                                                                              # Environment variable for staging 

# Service configuration for the staging deployment
service: 
  type: ClusterIP                                                                                            # Service type for staging  
  port: 80                                                                                                   # Staging service port 

# Staging Ingress configuration
ingress:
  enabled: true                                                                                              # Enable Ingress for staging  
  className: alb-staging                                                                                     # Ingress class for staging ALB 
  certificateArn: arn:aws:acm:us-east-1:688567307365:certificate/6b6f846b-571c-4c55-a140-e9217164e90a        # ACM certificate ARN for staging Ingress
  annotations:
    alb.ingress.kubernetes.io/scheme: internet-facing                                                        # Ingress scheme for staging   
    alb.ingress.kubernetes.io/listen-ports: '[{"HTTPS": 443}]'                                               # Ingress listen ports for staging
    alb.ingress.kubernetes.io/target-type: ip                                                                # Target type for staging Ingress
  path: /                                                                                                    # Path for staging Ingress
  pathType: Prefix                                                                                           # Path type for staging Ingress
  host: hello-world-staging-alb.tvedana.com                                                                  # Host for staging Ingress